import json
import re
import subprocess
from pathlib import Path

from .. import log
from ..settings import settings


def _redact(cmd: list[str], secrets: set[str]) -> list[str]:
    return ["***" if part in secrets else part for part in cmd]


def _apply_option_values(node, options: dict[str, dict[str, str]]) -> int:
    """Walk Morphe's own options JSON and set the requested option values.

    The schema is produced by ``options-create`` so we never guess it: any
    dict that carries a patch name (as key or as "name"/"patchName") and an
    "options" mapping gets updated in place. Returns how many were changed.
    """
    changed = 0
    if isinstance(node, dict):
        for key, value in node.items():
            if key in options and isinstance(value, dict):
                opts = value.get("options")
                if isinstance(opts, dict):
                    opts.update(options[key])
                    value["enabled"] = True
                    changed += 1
                    continue
            changed += _apply_option_values(value, options)
        name = node.get("patchName") or node.get("name")
        if isinstance(name, str) and name in options and isinstance(node.get("options"), dict):
            node["options"].update(options[name])
            node["enabled"] = True
            changed += 1
    elif isinstance(node, list):
        for item in node:
            changed += _apply_option_values(item, options)
    return changed


def _write_options_file(
    desktop: str,
    patches: list[str],
    options: dict[str, dict[str, str]],
    target: Path,
) -> bool:
    """Generate an options file with Morphe itself, then set our values in it."""
    cmd = ["java", "-jar", desktop, "options-create", "-o", str(target)]
    for p in patches:
        cmd += ["-p", p]
    result = subprocess.run(cmd, capture_output=True, text=True, check=False)
    if result.returncode != 0 or not target.exists():
        log.warn(f"options-create failed (exit {result.returncode}): {result.stderr.strip() or result.stdout.strip()}")
        return False

    data = json.loads(target.read_text(encoding="utf-8"))
    changed = _apply_option_values(data, options)
    if changed == 0:
        log.warn("Could not find the requested patch(es) in the generated options file.")
        return False

    target.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    log.step(f"Options file ready: {changed} patch entr{'y' if changed == 1 else 'ies'} updated")
    return True


def patch_apk(
    desktop: str,
    patches: list[str],
    apk: str,
    exclude: list[str] | None = None,
    enable: list[str] | None = None,
    options: dict[str, dict[str, str]] | None = None,
    arch: str = "arm64-v8a",
) -> str:
    log.patch(f"Patching APK & stripping unused architectures ({arch} only)...")

    ks_path = settings.ks_path
    ks_password = settings.ks_password.get_secret_value() if settings.ks_password else None
    ks_alias = settings.ks_alias
    key_password = settings.key_password.get_secret_value() if settings.key_password else None

    cmd = ["java", "-jar", desktop, "patch"]

    for p in patches:
        cmd += ["--patches", p]

    if arch:
        cmd += ["--striplibs", arch]

    if ks_path and ks_path.exists() and ks_password and ks_alias and key_password:
        log.lock("Custom keystore detected! Signing with your private key...")
        cmd += [
            "--keystore",
            str(ks_path),
            "--keystore-password",
            ks_password,
            "--keystore-entry-alias",
            ks_alias,
            "--keystore-entry-password",
            key_password,
        ]
    else:
        log.warn("Custom keystore credentials missing or file not found. Falling back to default Morphe testkey.")

    # Options go through an options JSON file (generated by Morphe itself, so
    # the schema is always right). Plain -O flags are bound positionally and
    # are silently ignored when they don't match, which left "Custom branding"
    # on its default name ("YouTube Morphe").
    option_enabled_patches: set[str] = set(options or {})
    if options:
        options_path = Path(apk).with_name("morphe-options.json")
        if _write_options_file(desktop, patches, options, options_path):
            cmd += ["--options-file", str(options_path)]
            for patch_name in options:
                cmd += ["--enable", patch_name]
        else:
            log.warn("Falling back to -O flags for patch options.")
            for patch_name, opts in options.items():
                cmd += ["--enable", patch_name]
                for key, value in opts.items():
                    cmd.append(f"-O{key}={value}")

    for p in exclude or []:
        cmd += ["--disable", p]

    for p in enable or []:
        if p not in option_enabled_patches:
            cmd += ["--enable", p]

    cmd.append(apk)

    secret_values = {v for v in (ks_password, key_password) if v}
    log.step(f"Executing command: {' '.join(_redact(cmd, secret_values))}")

    process = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
    )
    assert process.stdout is not None

    output_lines = []
    for line in process.stdout:
        log.patch_line(line)
        output_lines.append(line)

    process.wait()
    output = "".join(output_lines)

    if "Applying 0 patches" in output:
        raise RuntimeError("Applying 0 patches. No compatible patch found or version not supported.")

    if process.returncode != 0:
        raise RuntimeError(f"Patch failed (exit {process.returncode}):\n{output}")

    match = re.search(r"INFO:\s+Saved to\s+([^\r\n]+\.apk)", output, re.IGNORECASE)
    if not match:
        raise RuntimeError(f"Cannot find patched APK path in output:\n{output}")

    patched_apk = match.group(1).strip()

    if not Path(patched_apk).exists():
        raise RuntimeError(f"Patched APK does not exist:\n{patched_apk}")

    log.success("Patch done")
    log.saved(f"Output: {patched_apk}")

    return patched_apk
