name: Patch Morphe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write
      actions: write
      id-token: write
      attestations: write
      artifact-metadata: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb google-chrome-stable
          pip install -r requirements.txt

      - name: Setup Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > Panemi.keystore

      - name: Run Patcher
        run: xvfb-run python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          TARGET_APP: "all"
          KS_PATH: "Panemi.keystore"
          KS_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KS_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Generate Provenance
        uses: actions/attest@v4
        with:
          subject-path: |
            *.apk
            !microg*.apk

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 1
